server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/3LabComputer
    username: postgres
    password: Postgresql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: Computer

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
